// AUTO-GENERATED by typescript-type-def

export type AuthRequestBody={"password":string;};
export type AuthResponseSuccess={"token":string;};
export type GenericError={"error":string;};
export type GenericResponse<T,E>=(({"type":"Success";}&T)|({"type":"Error";}&E));
export type SetPasswordResponse=(({"type":"Success";}&{"message":string;})|({"type":"PasswordHasAlreadyBeenSetError";}&{"message":string;})|({"type":"GenericError";}&{"message":string;}));
export type __AllTyps=[AuthRequestBody,GenericResponse<AuthResponseSuccess,GenericError>,AuthRequestBody,SetPasswordResponse];
